version: "3"
services:
  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:80"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql_host
      - DB_PORT=3307
      - DB_DATABASE=learnwise
      - DB_USERNAME=root
      - DB_PASSWORD=mysecret
      - SSL_MODE=off
    env_file:
      - .env
    networks:
      - web-dev

  mysql:
    hostname: mysql_host
    restart: unless-stopped
    platform: linux/x86_64
    image: "mysql:5.7"
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --explicit_defaults_for_timestamp
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_DATABASE: learnwise
    volumes:
      - database:/var/lib/mysql
    networks:
      - web-dev

networks:
  web-dev:

volumes:
  database:
