version: "3"
services:
  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:80"
    environment:
      - SSL_MODE=off
    env_file:
      - .env
    networks:
      web-dev:
        aliases:
          - host.docker.internal

networks:
  web-dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
