version: "3"
services:
  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:80"
    environment:
      - SSL_MODE=off
    env_file:
      - .env
    networks:
      - bridge

volumes:
  database:
